config/routes.rb
Rails.application.routes.draw do

  get 'chat/message'
  post 'chat/message' => 'chat#message'
  post 'games/play_turn' => 'games#play_turn'

  devise_for :users
  get 'welcome' => 'welcome#index'
  get 'card_list' => 'welcome#card_list'
  get 'instructions' => 'welcome#instructions'
  get 'about_us' => 'welcome#about_us'
  get 'gamewindow' => 'welcome#gamewindow'

  root 'games#index'

  resources :games do
    get 'join'
    post 'start'
    get 'leave'
    get 'draw'
    post 'send_chat'
    post 'play_card'
    post 'give_card_to_thief'
  end

  resources :users

end

app/views/nav/_navbar.html.erb
<nav class="navbar navbar-custom" role="navigation" id ="nav">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse"
      data-target="#myNavbar">
      <!-- ≡ button -->
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Exploding Kittens</a>
  </div>
  <div class="collapse navbar-collapse" id="myNavbar">
    <ul class="nav navbar-nav navbar-right"> <!-- Links to the right -->
      <li><a href="/">Home</a></li>
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown"
        href="#">Play Game<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Create a new game', '', data: { toggle: 'modal', target: '#new_game_form' } %></li>
          <li><%= link_to 'List of games', games_path %></li>
          <li><%= link_to 'Players & Stats', users_path %></li>
        </ul>
      </li>
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown"
        href="#">How to Play<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="instructions">Instructions</a></li>
          <li><a href="card_list">Card List</a></li>
        </ul>
      </li>
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown"
        href="#">About Us<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="about_us">Developers</a></li>
        </ul>
      </li>
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown"
        href="#">Settings<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to "Settings", edit_user_registration_path %></li>
          <li><%= link_to('Log out', destroy_user_session_path, :method => :delete) %></li>
        </ul>
      </li>
    </ul>
  </div>
</div>
</nav>

<%= render 'games/form' %>